spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
      auto-offset-reset: latest
    producer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
