spring:
  datasource:
    # В проде используем переменные окружения для указания логинов, паролей и урлов
    username: ${MENU_DB_USER}
    password: ${MENU_DB_PASSWORD}
    url: ${MENU_DB_URL}
  jpa:
    properties:
      hibernate:
        # в проде выключаем показ sql запросов
        show_sql: false
