spring:
  datasource:
    # В проде используем переменные окружения для указания логинов, паролей и урлов
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    properties:
      hibernate:
        # в проде выключаем показ sql запросов
        show_sql: false

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  zipkin-endpoint: ${ZIPKIN_URL}
  keycloak-url: ${KEYCLOAK_URL}
  jwk-set-url: ${JWK_SET_URL}