spring:
  # В проде используем переменные окружения для указания логинов, паролей и урлов
  r2dbc:
    username: ${ORDERS_DB_USER}
    password: ${ORDERS_DB_PASSWORD}
    url: ${ORDERS_DB_URL}
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${ORDERS_FLYWAY_DB_URL}

external:
  menu-service-url: ${MENU_SERVICE_URL}
  # В проде увеличиваем таймаут, который будет использоваться при связи с Menu Service
  default-timeout: 5s