spring:
  # В проде используем переменные окружения для указания логинов, паролей и урлов
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  # В проде увеличиваем таймаут, который будет использоваться при связи с Menu Service
  default-read-timeout: 5s
  zipkin-endpoint: ${ZIPKIN_URL}
  loki-url: ${LOKI_URL}