spring:
  # В проде используем переменные окружения для указания логинов, паролей и урлов
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # в проде выключаем показ sql запросов
        show_sql: false

