spring:
  # В проде используем переменные окружения для указания логинов, паролей и урлов
  datasource:
    username: ${REVIEWS_DB_USER}
    password: ${REVIEWS_DB_PASSWORD}
    url: ${REVIEWS_DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
        # в проде выключаем показ sql запросов
        show_sql: false

